import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
// import { Navbar } from "@/components/ui/mini-navbar";
// import Footer from "@/components/footer";
import { Navbar } from "./navbar";
import { FloatingDockFooter } from "./footer";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "OpenDocs | Open Source Docs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} dark antialiased`}>
        <Navbar className="top-10" />
        {/* <Navbar /> */}
        {children}
        {/* <Footer /> */}
        <FloatingDockFooter />
      </body>
    </html>
  );
}


